package com.dashihui.afford.thirdapi.greedsqlite;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SEARCH.
 */
public class Search {

    private Long id;
    private long ID;
    /** Not-null value. */
    private String query;
    private Long date;

    public Search() {
    }

    public Search(Long id) {
        this.id = id;
    }

    public Search(Long id, long ID, String query, Long date) {
        this.id = id;
        this.ID = ID;
        this.query = query;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getID() {
        return ID;
    }

    public void setID(long ID) {
        this.ID = ID;
    }

    /** Not-null value. */
    public String getQuery() {
        return query;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setQuery(String query) {
        this.query = query;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

}
