package com.dashihui.afford.thirdapi.greedsqlite;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SERVER.
 */
public class Server {

    private Long id;
    /** Not-null value. */
    private String ID;
    /** Not-null value. */
    private String ShopID;
    private String brandname;
    private String name;
    private String thumb;
    private String comment;
    private String marketprice;
    private String sellprice;
    private String title;
    private String serverID;
    private String shortinfo;
    private String buynum;
    private Boolean ischoose;

    public Server() {
    }

    public Server(Long id) {
        this.id = id;
    }

    public Server(Long id, String ID, String ShopID, String brandname, String name, String thumb, String comment, String marketprice, String sellprice, String title, String serverID, String shortinfo, String buynum, Boolean ischoose) {
        this.id = id;
        this.ID = ID;
        this.ShopID = ShopID;
        this.brandname = brandname;
        this.name = name;
        this.thumb = thumb;
        this.comment = comment;
        this.marketprice = marketprice;
        this.sellprice = sellprice;
        this.title = title;
        this.serverID = serverID;
        this.shortinfo = shortinfo;
        this.buynum = buynum;
        this.ischoose = ischoose;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getID() {
        return ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setID(String ID) {
        this.ID = ID;
    }

    /** Not-null value. */
    public String getShopID() {
        return ShopID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setShopID(String ShopID) {
        this.ShopID = ShopID;
    }

    public String getBrandname() {
        return brandname;
    }

    public void setBrandname(String brandname) {
        this.brandname = brandname;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getThumb() {
        return thumb;
    }

    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getMarketprice() {
        return marketprice;
    }

    public void setMarketprice(String marketprice) {
        this.marketprice = marketprice;
    }

    public String getSellprice() {
        return sellprice;
    }

    public void setSellprice(String sellprice) {
        this.sellprice = sellprice;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getServerID() {
        return serverID;
    }

    public void setServerID(String serverID) {
        this.serverID = serverID;
    }

    public String getShortinfo() {
        return shortinfo;
    }

    public void setShortinfo(String shortinfo) {
        this.shortinfo = shortinfo;
    }

    public String getBuynum() {
        return buynum;
    }

    public void setBuynum(String buynum) {
        this.buynum = buynum;
    }

    public Boolean getIschoose() {
        return ischoose;
    }

    public void setIschoose(Boolean ischoose) {
        this.ischoose = ischoose;
    }

}
