package com.dashihui.afford.thirdapi.greedsqlite;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SHOPPING_CART.
 */
public class ShoppingCart {

    private Long id;
    /** Not-null value. */
    private String ID; //商品ID
    /** Not-null value. */
    private String ShopID; //店铺ID
    private String brandname;
    private String name;
    private String spec;
    private String shortinfo;
    private String marketprice;
    private String imgsrc;
    private String urv;
    private String type;
    private String sellprice;
    private String buynum;
    private String shoptype;//是否是自营商品：0：不是，1：是。
    private Boolean ischoose;

    public ShoppingCart() {
    }

    public ShoppingCart(Long id) {
        this.id = id;
    }

    public ShoppingCart(Long id, String ID, String ShopID, String brandname, String name, String spec, String shortinfo, String marketprice, String imgsrc, String urv, String type, String sellprice, String buynum, String shoptype, Boolean ischoose) {
        this.id = id;
        this.ID = ID;
        this.ShopID = ShopID;
        this.brandname = brandname;
        this.name = name;
        this.spec = spec;
        this.shortinfo = shortinfo;
        this.marketprice = marketprice;
        this.imgsrc = imgsrc;
        this.urv = urv;
        this.type = type;
        this.sellprice = sellprice;
        this.buynum = buynum;
        this.shoptype = shoptype;
        this.ischoose = ischoose;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getID() {
        return ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setID(String ID) {
        this.ID = ID;
    }

    /** Not-null value. */
    public String getShopID() {
        return ShopID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setShopID(String ShopID) {
        this.ShopID = ShopID;
    }

    public String getBrandname() {
        return brandname;
    }

    public void setBrandname(String brandname) {
        this.brandname = brandname;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSpec() {
        return spec;
    }

    public void setSpec(String spec) {
        this.spec = spec;
    }

    public String getShortinfo() {
        return shortinfo;
    }

    public void setShortinfo(String shortinfo) {
        this.shortinfo = shortinfo;
    }

    public String getMarketprice() {
        return marketprice;
    }

    public void setMarketprice(String marketprice) {
        this.marketprice = marketprice;
    }

    public String getImgsrc() {
        return imgsrc;
    }

    public void setImgsrc(String imgsrc) {
        this.imgsrc = imgsrc;
    }

    public String getUrv() {
        return urv;
    }

    public void setUrv(String urv) {
        this.urv = urv;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getSellprice() {
        return sellprice;
    }

    public void setSellprice(String sellprice) {
        this.sellprice = sellprice;
    }

    public String getBuynum() {
        return buynum;
    }

    public void setBuynum(String buynum) {
        this.buynum = buynum;
    }

    public String getShoptype() {
        return shoptype;
    }

    public void setShoptype(String shoptype) {
        this.shoptype = shoptype;
    }

    public Boolean getIschoose() {
        return ischoose;
    }

    public void setIschoose(Boolean ischoose) {
        this.ischoose = ischoose;
    }

}
